services:
  mysql:
    image: mysql:8.0
    container_name: weather_mysql
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: weather_etl
      MYSQL_USER: weather_user
      MYSQL_PASSWORD: weather_pass
