"""create weather_hourly

Revision ID: e9e9bd12964e
Revises: 
Create Date: 2026-04-05 11:18:33.266789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9e9bd12964e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weather_hourly',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('forecast_time', sa.DateTime(), nullable=False),
    sa.Column('temperature_2m', sa.Float(), nullable=True),
    sa.Column('relative_humidity_2m', sa.Float(), nullable=True),
    sa.Column('apparent_temperature', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('city', 'forecast_time', name='uq_city_forecast_time')
    )
    op.create_index(op.f('ix_weather_hourly_city'), 'weather_hourly', ['city'], unique=False)
    op.create_index(op.f('ix_weather_hourly_forecast_time'), 'weather_hourly', ['forecast_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weather_hourly_forecast_time'), table_name='weather_hourly')
    op.drop_index(op.f('ix_weather_hourly_city'), table_name='weather_hourly')
    op.drop_table('weather_hourly')
    # ### end Alembic commands ###
